server:
  port: 8080
  servlet:
    context-path: /identity
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/database"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "ubFGwHTndGElujrRWZHg+Li8J5QQq3gZ+0S92OcIrusBBDfuenvxwMpSEW+NBo1k"
  valid-duration: 60
  refreshable-duration: 120